apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
        - name: expense-backend
          image: siva9666/wages-backend:k8s-alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: expense-backend-config
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: expense-backend-config
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: expense-backend-secret
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: expense-backend-secret
                  key: DB_PWD
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
      restartPolicy: Always