apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
spec:
  ports:
    - port: 8080
  selector:
    project: expense
    component: backend
