apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: expense
  labels:
    project: expense
    component: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    project: expense
    component: frontend
