apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
spec:
  containers:
  - name: debug
    image: siva9666/debug:2.0
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
