apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: expense
  labels:
    project: expense
    component: mysql
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    project: expense
    component: mysql
