---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: expense
  labels:
    project: expense
    component: mysql
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
  replicas: 1
  template:
    metadata:
      labels:
        project: expense
        component: mysql
    spec:
      containers:
        - name: mysql
          image: siva9666/wages-db:k8s
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: expense-mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: expense-mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
